name: love_dogs
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  http: ^1.1.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  routemaster: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.6
  ficcanaso: ^6.0.1+1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
